- docs/supported-content-types-list.md
new colums are ->Index, Content Type Label ,Description
> Removed MIME Type Column from supported  list

- rust/CHANGELOG.md
- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/rustfmt.toml
- rust/src/builder.rs
- rust/src/config.rs
- rust/src/error.rs
- rust/src/input.rs
- rust/src/main.rs
- rust/src/output.rs
- rust/src/session.rs
There are quite some TODOs that can be addressed later (some can't be addressed now because they are blocked on something else). This is mostly to get the overall structure.
> Initial implementation of the Rust CLI

- README.md
- python/.dockerignore
- python/Dockerfile
Add Docker file for Magika Python
> feat: Add magika docker file

- rust/Cargo.toml
- rust/src/config.rs
- rust/src/input.rs
- rust/src/lib.rs
- rust/src/main.rs
- rust/src/session.rs
> Fix feature extraction to match Python

- .github/workflows/rust-test.yml
- rust/Cargo.lock
- rust/Cargo.toml
- rust/README.md
- rust/src/builder.rs
- rust/src/config.rs
- rust/src/error.rs
- rust/src/main.rs
- rust/src/session.rs
- rust/test.sh
> Switch Rust dependency from onnxruntime to ort

- .github/scorecard.yml
Tell our scorecard (https://securityscorecards.dev/viewer/?uri=github.com/google/magika) that test files are not security issues.
See https://github.com/ossf/scorecard/blob/main/config/README.md for the syntax
> Scorecard configuration

- assets_generation/assets_generation/generate_models_readmes.py
This generates a README that lists the supported content types.
> assets: add script to generate README for the models

- rust/cli/CHANGELOG.md
- rust/cli/Cargo.toml
- rust/cli/src/main.rs
This should only make a difference for Windows builds.
> Make sure telemetry is disabled

- python/src/magika/types/statusor.py
- python/tests/test_magika_python_module.py
__str__ attempted to access .value even with a non-OK status.
> python: fix __str__ of StatusOr

- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
> python: fail gracefully when api is called with wrong arg type

- .github/workflows/python-e2e-test.yml
- Test on all python versions
- Test on all OSes
Close #703.
> gh actions: re-enable build/testing on all config

- python/pyproject.toml
> python: update pyproject.toml with metadata

- python/scripts/build_python_package.py
Updates:
- patch linux wheels so that they are compatible with manylinux1
- Extra: add --allow-git-dirty-state CLI option
> python: build manylinux package

- README.md
- python/README.md
> docs: Add monthly downloads stats badge

- rust/cli/CHANGELOG.md
- rust/cli/src/main.rs
- rust/cli/test.sh
> Exit with non-zero code if at least one error was encountered

- .github/workflows/maturin.yml
Currently checking this only for ubuntu and macOS
> python: attempt to `uv add magika` when building packages

- .github/workflows/python-build-package.yml
Pin python version to 3.12 for the build package workflow.
> Pin to python 3.12 for python-build-package.yml

- rust/cli/CHANGELOG.md
- rust/cli/Cargo.lock
- rust/cli/Cargo.toml
- rust/cli/src/main.rs
- rust/lib/CHANGELOG.md
- rust/lib/Cargo.lock
- rust/lib/Cargo.toml
- rust/lib/src/builder.rs
- rust/lib/src/future.rs
- rust/lib/src/session.rs
- rust/onnx/build.sh
> Pin ort version and update vulnerable rustls

- tests_data/basic/zig/code.zig
This PR introduce zig  language. Related with https://github.com/google/magika/issues/662
> feat: add zig code to test_data basic

- assets/models/standard_v3_0/README.md
> assets: Improve model's documentation

- .github/workflows/python-build-package.yml
> build: for Windows' builds, keep building in case of mispredictions

- .github/workflows/python-build-package.yml
- .github/workflows/python-test-published-rc-package.yml
- python/scripts/run_quick_test_magika_module.py
- python/src/magika/magika.py
This prints the module version and model name; it helps for debugging.
> python: implement str() and repr() for Magika object

- assets/models/CHANGELOG.md
> assets: add first model's changelog

- python/CHANGELOG.md
- python/pyproject.toml
- python/uv.lock
Fixes #922.
Merge only after having taken care of https://github.com/google/magika/issues/924.
> python: add back constrains for onnxruntime

- README.md
- python/README.md
> docs: update bibtex entry to point to ICSE'25 paper

- .github/workflows/docs-check.yml
- python/scripts/check_documentation.py
> docs: add script to check documentation (for now, links)

- python/CHANGELOG.md
- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
> python: make identify_path(s) accepting str

- python/scripts/check_documentation.py
Now we check that the python stable version and the models versions are up to date:
- We get the latest stable version by querying pypi.
- We get the latest model version by grepping in `magika.py`.
- We then check that the READMEs use the up to date versions.
Context: #968.
> docs: improve check documentation script

- python/scripts/check_documentation.py
> docs: add rust docs tracking to check docs script

- website/src/components/Homepage.vue
> Add notice on website about the new magika model

- python/CHANGELOG.md
- python/README.md
> Python: prepare 0.6.1 release

- website/src/components/FileClassifierDemo.vue
- website/src/components/Homepage.vue
- website/src/components/TextAreaClassifierDemo.vue
- website/yarn.lock
> Website textarea demo

- website/src/components/Homepage.vue
This is how it looks on mobile: ![Screenshot_20250408-114754](https://github.com/user-attachments/assets/033cae27-a8ff-45b2-ac8e-37c77fa2af19)
> website: display informative message if the demo is not available

- rust/cli/CHANGELOG.md
- rust/cli/Cargo.lock
- rust/cli/Cargo.toml
- rust/lib/CHANGELOG.md
- rust/lib/Cargo.lock
- rust/lib/Cargo.toml
> Release Rust crates

- js/.gitignore
- js/README.md
- js/magika-node.ts
- js/package.json
- js/simple_examples/browser-esmodule-example/index.html
- js/simple_examples/browser-esmodule-example/index.js
- js/simple_examples/browser-esmodule-example/package.json
- js/simple_examples/browser-esmodule-example/playwright.config.ts
- js/simple_examples/browser-esmodule-example/test/simple.spec.ts
- js/simple_examples/node-commonjs-example/index.js
- js/simple_examples/node-commonjs-example/package.json
- js/simple_examples/node-esmodule-example/index.js
- js/simple_examples/node-esmodule-example/package.json
- js/simple_examples/run_examples.sh
- js/simple_examples/typescript-esmodule-example/index.ts
- js/simple_examples/typescript-esmodule-example/package.json
- js/yarn.lock
This commit fixes #299 and adds some additional examples / tests of various JS/TS use configurations to ensure MagikaJS works correctly in all configs.
> Fixes JS imports (issue #299) 

- .github/workflows/js-check-import-scenarios.yml
It's running out of disk space
> Reduce action size for js-check-import-scenarios

- js/package.json
- js/yarn.lock
> Revert "build(deps): bump commander from 13.1.0 to 14.0.1 in /js"
