google/magika

- js/magika.js
The `modelURL` is also used as `configURL`
https://github.com/google/magika/blob/59c4cd76367020662e5148363aee2df1102acdc4/js/magika.js#L74-L75
This will cause a weird error to be thrown:
```error
Uncaught (in promise) RangeError: offset is out of bounds
at Uint16Array.set (<anonymous>)
at Magika._extractFeaturesFromBytes (magika.js:182:9)
at Magika._identifyBytes (magika.js:143:53)
at Magika.identifyBytes (magika.js:92:17)
at fileReader.onload (index.tsx:141:40)
```
> fix: use correct configURL for magika JS

- js/magika.js
This fixes the following error when using `magika.load()`:
```error
TypeError: Cannot destructure property 'modelURL' of 'undefined' as it is undefined.
```
> The current workaround is to use `magika.load({})`, which does not seem intuitive, and is also not what's described in the documentation.
---
As a side note, I was thinking of creating a constructor method in the `Magika` class that will perform the `Magika.load` operation by default, passing in the load options into the constructor. What do you think?
> fix: initialise default load options in `Magika` class (npm/js)

- .github/workflows/e2e-test.yml
- .github/workflows/pkg-test.yml
Automates the process of building `magika` python wheel, installing the wheel and running `magika` against the files in `tests_data/`. If unable it will fail the CI job.
The test is run against py38 -> py3.12 using both Linux, MacOS, and Windows.
Fixes #158
> Add e2e testing of Python package using GitHub Actions

- js/magika.js
Continuation of #52 
It is discouraged from using async functions in constructor methods in JavaScript. Instead, I implemented an alternative way to initialise the `Magika` class in 1 call.
Now there are 2 ways (both will achieve the same results). This way, we have a more efficient way to initialise the class, but we also preserve the original way for backwards compatibility.
```js
const magika = new Magika();
await magika.load();
```
or
```js
const magika = await Magika.create();
```
Both `load` and `create` function take in an optional parameter with a default parameter.
> feat: initialise and load class in 1 call (npm/js)

- .github/ISSUE_TEMPLATE/new_content_type_request.md
- docs/js.md
I've seen some [NEW CONTENT TYPE REQUEST] issues that misunderstand the template. People think that the bullet points are part of one big example of a list. They are intended as a list of individual examples. I thought that the quotation marks, and entire comma separated lists under one bullet point made that clear when I wrote it. You don't need to use bullet points for one item, or keep the word "Examples", like [this](https://github.com/google/magika/issues/291), or [this](https://github.com/google/magika/issues/269), or [this](https://github.com/google/magika/issues/240), or [this](https://github.com/google/magika/issues/230), or [this](https://github.com/google/magika/issues/229), or [this](https://github.com/google/magika/issues/228), or, …
> Make examples more clear

- .github/workflows/js-docs-builder.yml
Automatic doc generation for `/js` works, but the commit to the main branch fails because of branch protection. Disable that feature for now.
> Disable automatic doc generation 

- rust/cli/output
- rust/cli/test.sh
> Update Rust tests to also run on previous_missdetections

- python/magika/types/strenum.py
- python/poetry.lock
- python/pyproject.toml
New versions of mypy raises an error for a method in strenum.py; for the moment, added an explicit ignore annotation for it.
Close #633, #637.
> python: ignore mypy errors for strenum, bump mypy version

- .github/workflows/rust-test.yml
- rust/changelog.sh
To make sure we don't forget to log how the library and CLI change, since this can happen by actions taking outside the Rust realm (like updating the model or changing thresholds).
> Add changelog test for Rust

- rust/cli/CHANGELOG.md
- rust/cli/src/main.rs
The default is the package name which is `magika-cli`. We want to use the binary name which is `magika`. Feature request on `clap` side: https://github.com/clap-rs/clap/issues/5738.
> Fix CLI name in --version

- python/scripts/build_python_package.py
This implements a script to build the python package. While in theory this would just be `uv build`, we are hitting a number of problems / corner cases with maturin. This script implements a temporary solution to workaround all existing problems; we'll clean up as soon as the underlying tooling gets better.
Closes #566.
> python: script to build python package

- python/src/magika/__init__.py
- python/src/magika/logger.py
- python/src/magika/magika.py
- python/src/magika/types/__init__.py
- python/src/magika/types/content_type_info.py
- python/src/magika/types/magika_error.py
- python/src/magika/types/magika_result.py
- python/src/magika/types/statusor_magika_result.py
- python/tests/test_magika_python_module.py
This PR makes progress on two aspects:
- simplify access to Magika's API results
- implement a backward compatibility layer, add deprecation warnings, and error out with meaningful messages when we cannot be fully backward compatible.
More context in the description of the two commits.
> python: improve API usability and add backward compatibility layer

- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
Closes #271.
Closes #571.
Closes #712.
> python: add API to get list of supported content types & fix ModelConfig types

- .github/workflows/python-e2e-test.yml
- .github/workflows/python-test-suite.yml
- python/scripts/build_python_package.py
- python/scripts/run_quick_test_magika_cli.py
- python/scripts/run_quick_test_magika_module.py
Improve the python gh action tests:
- clean up the gh action that runs the test suite.
- improve e2e gh action: it builds the package, it installs the package with pip, it runs the magika CLI (the rust one) and the Magika python module against all basic samples and checks for correct predictions.
> gh actions: improve python testing

- python/scripts/run_quick_test_magika_module.py
- python/src/magika/__init__.py
This allows to import `ContentTypeLabel` from the top magika module.
This is useful in situations like:
```
res = magika.identify_path(...)
if res.output.label == ContentTypeLabel.PYTHON:
...
```
> Python: allow to import `ContentTypeLabel` from `magika` module

- .github/CODEOWNERS
- .github/workflows/rust-test.yml
- rust/cli/src/main.rs
- rust/lib/test.sh
- rust/publish.sh
- Fix build on recent nightly.
- Fix publish script to correctly update changelog files.
- Don't cross-compile since the CI does it.
- Removing myself from default code owners (keeping only Rust).
> Few Rust fixes

- README.md
Two of the badges were pointing to a different project by mistake; fixed the CodeQL URL and removed the codecov one
> readme: fix badge urls

- rust/cli/src/main.rs
It was disabled by #726 due to a false positive tracked and fixed by https://github.com/rust-lang/rust-clippy/issues/13458.
> Re-enable clippy lint

- rust/color.sh
This is currently only used in tail position, so the bug is not visible.
> Fix success helper function not exiting

- .github/workflows/maturin.yml
- python/scripts/fix_package_version.py
Of course in #747 I only checked the Linux wheel, not the sdist one. This PR fixes the version for sdist too.
[Here](https://github.com/google/magika/actions/runs/11530715610) are the wheels for inspection (only metadata inspection is needed, the workflow already runs the tests and the versions can be read in the output, including the wheel version).
> Also fix version in maturin sdist

- .github/workflows/maturin.yml
- rust/cli/test.sh
We actually want to run the workflow on pull requests, simply not upload the artifacts. Otherwise we won't catch cases where a pull request breaks the "build".
> Fix maturin workflow

- rust/cli/CHANGELOG.md
- rust/cli/Cargo.lock
- rust/cli/Cargo.toml
- rust/cli/README.md
- rust/lib/CHANGELOG.md
- rust/lib/Cargo.lock
- rust/lib/Cargo.toml
I forgot to bump them since the last release (essentially changes from #760 and #784).
> Fix Rust lib and CLI versions

- python/CHANGELOG.md
- python/pyproject.toml
- python/src/magika/__init__.py
- python/uv.lock
`uv add onnxruntime` on MacOS currently fails as it resolves to 1.20.0, even if that can't be used on MacOS. This, in turns, make `uv add magika` fails as well.
Temporary fix is to help uv resolving to a proper version of onnxruntime.
Close #801.
> python: constraint onnxruntime version to fix uv/macos problems

- .github/workflows/python-build-package.yml
- .github/workflows/python-test-published-package.yml
- .github/workflows/python-test-published-rc-package.yml
Resolves #805 
Updated the following workflows to install `uv` and verify that `uv add magika.whl` works on windows runner:
* `.github/workflows/python-build-package.yml`
* `.github/workflows/python-test-published-package.yml`
* `.github/workflows/python-test-published-rc-package.yml`
> Extend magika wheels test to windows runner

- .github/workflows/rust-test.yml
- rust/gen/src/main.rs
Also do not fail the workflow when nightly fails. The situations where the nightly job fails but the stable job doesn't, shouldn't block merging a PR. In particular, nightly is not hermetic (by design), so shouldn't block merging a PR for this simple reason alone.
Fixes #867
> Fix nightly lints

- python/CHANGELOG.md
- python/scripts/magika_python_module_tester.py
- python/src/magika/magika.py
- python/src/magika/types/__init__.py
- python/src/magika/types/overwrite_reason.py
- python/tests/test_magika_python_module.py
Fixes #873.
This is useful to signal to external clients why and if the model's prediction was overwritten. As of now, it can either happen because of a low-confidence model prediction, or because of the model's overwrite_map config.
> python: add OverwriteReason field to MagikaPrediction

- .github/workflows/js-publish.yml
- .github/workflows/js-test.yml
- .github/workflows/python-build-package.yml
- .github/workflows/python-test-published-package.yml
- .github/workflows/python-test-published-rc-package.yml
- .github/workflows/python-test-suite.yml
- .github/workflows/rust-test.yml
Fixes #899.
FYI @ia0 @invernizzi
> Disable automatic git CRLF conversion at checkout

- rust/onnx/build.sh
GCC 14 is either better at detecting uninitialized issues or has false positives, compared to GCC 13. Those warnings are considered as errors, so we disable them.
> Disable some warnings when building ONNX Runtime

- .gitattributes
- .github/workflows/js-publish.yml
- .github/workflows/js-test.yml
- .github/workflows/python-build-package.yml
- .github/workflows/python-test-published-package.yml
- .github/workflows/python-test-published-rc-package.yml
- .github/workflows/python-test-suite.yml
- .github/workflows/rust-test.yml
This fixes #899 in a cleaner way, and somehow reverts #900.
> gh: disable crlf conversion on all platforms via gitattributes

- .github/workflows/python-build-package.yml
It got broken after bumping uv version, which is now installed in a different directory.
> fix windows build

- python/pyproject.toml
With a past version of uv, `uv add onnxruntime` would fail. To address that, we overly constrained the allowed onnxruntime version (#801).
More recent versions of uv have now fixed this
(https://github.com/astral-sh/uv/pull/9827), so we remove the constraint.
Fixes #835.
> python: relax constraint on onnxruntime

- .github/workflows/python-test-published-package.yml
- .github/workflows/python-test-published-rc-package.yml
Installing the latest -rc with uv still fails (#922), but this PR is useful anyways.
> gh workflow: bump uv version in public pip package testers

- .github/workflows/python-build-package.yml
> gh workflow: test the built wheels with different versions of python

- .github/workflows/python-build-package.yml
- python/scripts/prepare_pyproject_for_pure_python_wheel.py
- python/scripts/run_quick_test_magika_cli.py
- python/src/magika/cli/magika_rust_client_not_found_warning.py
Also, in the pure python wheel, "magika" now points to a small script that raises a warning and provide instructions.
Ref: #930.
Also: generate sdist alongside the pure python wheel. Fixes #919.
> Make the python client available as "magika-python-client" rather than "magika"

- README.md
- python/CHANGELOG.md
- python/README.md
- python/src/magika/__init__.py
- python/src/magika/magika.py
- python/src/magika/seekable.py
- python/tests/test_magika_python_module.py
This PR adds a new `identify_stream` API, as suggested in #970. With this API, one can identify the content type of an already-open stream; the implementation does not read the full file, and it just `seek()`s around. This new API avoids clients to be forced to (directly or indirectly) read the full file's content in memory.
Fixes #970.
> Python: add new `identify_stream` API

- python/CHANGELOG.md
- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
This helps disambiguate which "thing" the version is referring to.
> python: rename `get_version` => `get_module_version` method

- .github/workflows/python-build-package.yml
- .github/workflows/python-test-published-package.yml
- .github/workflows/python-test-published-rc-package.yml
- .github/workflows/python-test-suite.yml
- python/CHANGELOG.md
- python/pyproject.toml
- python/src/magika/__init__.py
Fixes: #811.
~Currently blocked as onnxruntime does not support python 3.13 yet.~ `onnxruntime 1.21.0` now supports python 3.13.
> Mark support for python 3.13 and add testing

- python/CHANGELOG.md
- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
> python bugfix: limit the number of bytes we read in case of an input with just many whitespaces

- python/CHANGELOG.md
- python/pytest.ini
- python/src/magika/types/content_type_info.py
We recently added a couple of `DeprecationWarning`s, and to make sure users would see them, we also set `warnings.simplefilter` to `always`. However, this inadvertently modified the warnings' settings for all other modules as well. This is not nice.
This patch removes the edit to the simplefilter (going back to default) and uses `stacklevel`s `warn` argument to increase the `DeprecationWarning` visibiilty. This is not a silver bullet as if one uses the deprecated property "three levels or more" deep, the warning is not visible.
To fix this limitation, python 3.12 added the `skip_file_prefixes` argument to `warn` (https://github.com/python/cpython/pull/100840), but it's not worth using it and break compatibility with older versions of python. `stacklevel=2` should not create any problems …
> python: do not alter warnings' filter

- python/CHANGELOG.md
- python/src/magika/magika.py
- python/tests/test_magika_python_module.py
`identify_stream()` now restores the stream's original position after reading from it, preventing side effects on subsequent stream operations.
Fixes #1018.
> python: identify_stream now seeks back to initial stream position before returning

- .github/workflows/github-pages.yml
`npm ci` correctly complains that there's no `package-lock.json`. We use yarn, so this makes sure to use that
> Update github-pages.yml to use yarn

- rust/gen/src/main.rs
- rust/lib/CHANGELOG.md
- rust/lib/src/config.rs
- rust/lib/src/input.rs
- rust/lib/src/model.rs
According to #1055 we have `mid_size == 0` and `use_inputs_at_offsets == false`. This simplifies the code significantly. The simplification is fine to do because we only support one model and it's embedded. Once we'll support multiple models (in particular dynamic loading), we'll need features extraction to work for all possible models (possibly having multiple features extraction functions).
> Simplify Rust code

- .github/CODEOWNERS
The `*.md` rule for documentation is a bit strong. The intent was only to capture READMEs under rust, so this PR explicitly excludes the CHANGELOGs from that rule. This makes it possible to do pure code changes to the Rust CLI and library without double approvals.
> Keep ia0 as owner of rust Changelogs

- .github/workflows/python-test-suite.yml
- python/changelog.sh
- python/scripts/check_changelog.sh
Fixes #963.
- Added changelog.sh script to detect undocumented Python code changes.
- Introduced a new changelog-check job in the Python - run test suite workflow.
- The job runs on pull requests and pushes that affect python/ workflows.
- Uses GitHub Actions annotation feature to display a warning if the changelog is missing.
@reyammer  Please let me know if there are any changes needed to be made
Thanks
> added files to give message some changes are not documented
